const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));let token=sessionStorage.getItem("school_admin")||"",state={classes:[],students:[],requests:[],reports:[]},path="";
async function api(url,opt={}){const h=new Headers(opt.headers||{});if(token)h.set("Authorization",`Bearer ${token}`);if(opt.json!==undefined){h.set("Content-Type","application/json");opt.body=JSON.stringify(opt.json)}return fetch(`/api/admin${url}`,{...opt,headers:h})}function note(t){$("notice").textContent=t;setTimeout(()=>$("notice").textContent="",3000)}
$("loginForm").onsubmit=async e=>{e.preventDefault();const r=await api("/login",{method:"POST",json:{username:$("adminName").value,password:$("adminPassword").value}}),d=await r.json();if(!r.ok){$("loginError").textContent=d.detail;return}token=d.token;sessionStorage.setItem("school_admin",token);showApp()};
function showApp(){$("login").classList.add("hidden");$("app").classList.remove("hidden");load()}if(token)showApp();
document.querySelector("nav").onclick=e=>{const b=e.target.closest("[data-view]");if(!b)return;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$(b.dataset.view).classList.remove("hidden");if(b.dataset.view==="recycle")loadRecycle();if(b.dataset.view==="files")loadFiles("")};
async function load(){const r=await api("/overview");if(!r.ok)return;state=await r.json();render()}
function render(){const opts=state.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");$("announcementClass").innerHTML=opts;$("studentSelect").innerHTML=`<option value="">选择学生</option>`+state.students.map(s=>`<option value="${s.id}">${esc(s.class_name)} / ${esc(s.username)}</option>`).join("");$("studentRows").innerHTML=state.students.map(s=>`<tr><td>${esc(s.class_name)}</td><td>${esc(s.username)}</td><td>${s.status==="active"?"正常":s.status==="disabled"?"已禁用":"待设置密码"}</td><td>${esc(s.used_display)}</td><td><div class="actions"><button onclick="editStudent(${s.id})">修改</button><button onclick="toggleStudent(${s.id},'${s.status}')">${s.status==="disabled"?"启用":"禁用"}</button><button class="danger" onclick="removeStudent(${s.id},'${esc(s.username)}')">删除</button></div></td></tr>`).join("");$("classRows").innerHTML=state.classes.map(c=>`<tr><td>${esc(c.name)}</td><td>storage/${esc(c.storage_key)}</td><td><div class="actions"><button onclick="renameClass(${c.id},'${esc(c.name)}')">改名</button><button class="danger" onclick="removeClass(${c.id})">删除空班级</button></div></td></tr>`).join("");$("requestRows").innerHTML=state.requests.map(r=>`<tr><td>${esc(r.class_name)}</td><td>${esc(r.username)}</td><td>${new Date(r.created_at).toLocaleString()}</td><td><button onclick="review(${r.id},true)">通过</button> <button onclick="review(${r.id},false)">拒绝</button></td></tr>`).join("");$("reportList").innerHTML=state.reports.map(r=>`<article class="report"><strong>${esc(r.class_name)} / ${esc(r.username)}</strong><p>${esc(r.content)}</p><span class="muted">${new Date(r.created_at).toLocaleString()}</span></article>`).join("")||"暂无汇报"}
async function editStudent(id){const s=state.students.find(x=>x.id===id),name=prompt("学生姓名",s.username);if(name===null)return;const classId=Number(prompt("班级ID\n"+state.classes.map(c=>`${c.id}: ${c.name}`).join("\n"),s.class_id));const password=prompt("新密码（不修改请留空）","");const r=await api(`/students/${id}`,{method:"PATCH",json:{username:name,class_id:classId,password}});note(r.ok?"学生信息已更新":(await r.json()).detail);load()}
async function toggleStudent(id,status){const next=status==="disabled"?"active":"disabled";if(!confirm(`确认${next==="disabled"?"禁用":"启用"}？`))return;await api(`/students/${id}`,{method:"PATCH",json:{status:next}});load()}
async function removeStudent(id,name){alert("请不要随意删除学生！账号将停用，学生目录会移入统一回收站。");if(prompt(`请输入学生姓名 ${name} 确认`)!==name)return;if(!confirm("最后确认删除该学生？"))return;const r=await api(`/students/${id}`,{method:"DELETE",json:{username:name,acknowledge:"我确认删除学生并将文件移入回收站"}});note(r.ok?"学生已删除，文件已移入回收站":(await r.json()).detail);load()}
$("addClass").onclick=async()=>{const name=prompt("新班级名称");if(!name)return;const r=await api("/classes",{method:"POST",json:{name}});note(r.ok?"班级已创建":(await r.json()).detail);load()};async function renameClass(id,old){const name=prompt("新班级名称",old);if(!name)return;const r=await api(`/classes/${id}`,{method:"PATCH",json:{name}});note(r.ok?"班级及目录已改名":(await r.json()).detail);load()}async function removeClass(id){if(!confirm("只能删除没有学生且目录为空的班级，确认？"))return;const r=await api(`/classes/${id}`,{method:"DELETE"});note(r.ok?"班级已删除":(await r.json()).detail);load()}async function review(id,approve){if(!confirm(approve?"通过申请并创建学生目录？":"拒绝该申请？"))return;const r=await api(`/requests/${id}/review`,{method:"POST",json:{approve}});note(r.ok?"申请已处理":(await r.json()).detail);load()}
$("announcementForm").onsubmit=async e=>{e.preventDefault();const r=await api("/announcements",{method:"POST",json:{class_id:Number($("announcementClass").value),title:$("announcementTitle").value,content:$("announcementContent").value}});note(r.ok?"公告已发布":(await r.json()).detail);if(r.ok)e.target.reset()};
$("studentSelect").onchange=()=>loadFiles("");$("upBtn").onclick=()=>loadFiles(path.includes("/")?path.slice(0,path.lastIndexOf("/")):"");$("mkdirBtn").onclick=async()=>{const name=prompt("文件夹名称");if(!name)return;await api(`/students/${$("studentSelect").value}/mkdir`,{method:"POST",json:{path,name}});loadFiles(path)};$("uploadBtn").onclick=()=>$("uploadInput").click();$("uploadInput").onchange=async e=>{const form=new FormData();form.append("path",path);[...e.target.files].forEach(f=>{form.append("files",f);form.append("relative_paths",f.name)});await api(`/students/${$("studentSelect").value}/upload`,{method:"POST",body:form});e.target.value="";loadFiles(path)};
async function loadFiles(next){const id=$("studentSelect").value;if(!id)return;const r=await api(`/students/${id}/files?path=${encodeURIComponent(next)}`);if(!r.ok)return;const d=await r.json();path=d.path;$("pathLabel").textContent="/"+path;$("fileRows").innerHTML=d.entries.map(x=>`<tr><td>${x.type==="folder"?`<button class="folder" data-open="${esc(x.path)}">📁 ${esc(x.name)}</button>`:esc(x.name)}</td><td>${x.type==="folder"?"文件夹":"文件"}</td><td>${esc(x.content_display)}</td><td>${esc(x.size_display)}</td><td>${x.type==="file"?`<button data-download="${esc(x.path)}">下载</button> `:""}<button data-rename="${esc(x.path)}" data-name="${esc(x.name)}">改名</button> <button class="danger" data-delete="${esc(x.path)}">删除</button></td></tr>`).join("")}
$("fileRows").onclick=async e=>{const id=$("studentSelect").value,b=e.target;if(b.dataset.open)return loadFiles(b.dataset.open);if(b.dataset.rename){const name=prompt("新名称",b.dataset.name);if(name){await api(`/students/${id}/rename`,{method:"POST",json:{path:b.dataset.rename,name}});loadFiles(path)}}if(b.dataset.delete&&confirm("删除后将进入统一回收站，确认？")){await api(`/students/${id}/delete`,{method:"POST",json:{path:b.dataset.delete}});loadFiles(path)}if(b.dataset.download){const r=await api(`/students/${id}/download?path=${encodeURIComponent(b.dataset.download)}`);const blob=await r.blob(),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=b.dataset.download.split("/").pop();a.click();URL.revokeObjectURL(a.href)}};
async function loadRecycle(){const r=await api("/recycle"),d=await r.json();$("recycleRows").innerHTML=d.items.map(x=>`<tr><td>${esc(x.class_name)}</td><td>${esc(x.username)}</td><td>${esc(x.original_path)}</td><td>${new Date(x.deleted_at).toLocaleString()}</td><td><button data-restore="${x.id}" data-user="${x.user_id}">恢复</button></td></tr>`).join("")||`<tr><td colspan="5">回收站为空</td></tr>`}$("recycleRows").onclick=async e=>{const b=e.target.closest("[data-restore]");if(!b)return;const r=await api(`/recycle/${b.dataset.restore}/restore`,{method:"POST",json:{user_id:Number(b.dataset.user)}});note(r.ok?"已恢复到学生原目录":(await r.json()).detail);loadRecycle()};
