const API="/api/admin";let adminToken=localStorage.getItem("admin_token")||"";let data={groups:[],users:[],requests:[]};let filePath="";
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function call(path,options={}){const headers=new Headers(options.headers||{});if(adminToken)headers.set("Authorization",`Bearer ${adminToken}`);if(options.json!==undefined){headers.set("Content-Type","application/json");options.body=JSON.stringify(options.json)}const r=await fetch(`${API}${path}`,{...options,headers});if(r.status===401){adminToken="";localStorage.removeItem("admin_token");showLogin()}return r}
function showLogin(){$("adminLogin").classList.remove("hidden");$("adminApp").classList.add("hidden")}
function showApp(){$("adminLogin").classList.add("hidden");$("adminApp").classList.remove("hidden");loadOverview()}
$("adminLoginForm").addEventListener("submit",async e=>{e.preventDefault();const r=await call("/login",{method:"POST",json:{username:$("adminUsername").value,password:$("adminPassword").value}});const d=await r.json();if(!r.ok){$("adminLoginError").textContent=d.detail;return}adminToken=d.token;localStorage.setItem("admin_token",adminToken);showApp()});
$("adminLogout").onclick=async()=>{await call("/logout",{method:"POST"});adminToken="";localStorage.removeItem("admin_token");showLogin()};
document.querySelector("nav").onclick=e=>{const b=e.target.closest("[data-panel]");if(!b)return;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".panel").forEach(x=>x.classList.add("hidden"));$(`${b.dataset.panel}Panel`).classList.remove("hidden");if(b.dataset.panel==="files")loadFiles("")};
async function loadOverview(){const r=await call("/overview");if(!r.ok)return;data=await r.json();render()}
function render(){const groupOptions=data.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join("");$("usersBody").innerHTML=data.users.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.group_name)}</td><td class="status-${u.status}">${u.status==="active"?"正常":"已禁用"}</td><td>${esc(u.used_display)} / ${(u.quota_bytes/1073741824).toFixed(1)} GB</td><td><div class="actions"><button onclick="toggleUser(${u.id},'${u.status}')">${u.status==="active"?"禁用":"启用"}</button><button onclick="editUser(${u.id})">设置</button><button class="danger" onclick="deleteUser(${u.id},'${esc(u.username)}')">删除</button></div></td></tr>`).join("");$("groupsBody").innerHTML=data.groups.map(g=>`<tr><td>${esc(g.name)}</td><td>${esc(g.created_at)}</td><td><button class="danger" onclick="deleteGroup(${g.id})">删除</button></td></tr>`).join("");$("requestsBody").innerHTML=data.requests.map(r=>`<tr><td>${esc(r.username)}</td><td>${esc(r.group_name)}</td><td>${esc(r.created_at)}</td><td><div class="actions"><button onclick="review(${r.id},true)">通过</button><button class="danger" onclick="review(${r.id},false)">拒绝</button></div></td></tr>`).join("");$("fileUserSelect").innerHTML=`<option value="">选择用户</option>`+data.users.map(u=>`<option value="${u.id}">${esc(u.group_name)} / ${esc(u.username)}</option>`).join("")}
function note(text){$("notice").textContent=text;setTimeout(()=>$("notice").textContent="",3000)}
async function addGroup(){const name=prompt("输入用户组名称");if(!name)return;const r=await call("/groups",{method:"POST",json:{name}});note(r.ok?"用户组已创建":(await r.json()).detail);loadOverview()}
async function deleteGroup(id){if(!confirm("仅空用户组可以删除，确认继续？"))return;const r=await call(`/groups/${id}`,{method:"DELETE"});note(r.ok?"用户组已删除":(await r.json()).detail);loadOverview()}
async function addUser(){const username=prompt("用户名");if(!username)return;const password=prompt("初始密码（至少6位）");if(!password)return;const groupId=Number(prompt("用户组ID：\n"+data.groups.map(g=>`${g.id}: ${g.name}`).join("\n")));const r=await call("/users",{method:"POST",json:{username,password,group_id:groupId}});note(r.ok?"用户已创建":(await r.json()).detail);loadOverview()}
async function toggleUser(id,status){const next=status==="active"?"disabled":"active";if(!confirm(`确认${next==="disabled"?"禁用":"启用"}该用户？`))return;await call(`/users/${id}`,{method:"PATCH",json:{status:next}});loadOverview()}
async function editUser(id){const user=data.users.find(x=>x.id===id);const quota=prompt("设置额度（GB）",(user.quota_bytes/1073741824).toFixed(1));if(quota===null)return;const password=prompt("设置新密码；不修改请留空","");const groupId=Number(prompt("用户组ID",user.group_id));const r=await call(`/users/${id}`,{method:"PATCH",json:{quota_bytes:Math.round(Number(quota)*1073741824),password,group_id:groupId}});note(r.ok?"用户设置已更新":(await r.json()).detail);loadOverview()}
async function deleteUser(id,username){alert("警告：不要随意删除用户！删除后用户将不能登录。文件会保留，但账号恢复需要人工处理。");const typed=prompt(`请输入用户名 ${username} 确认删除`);if(typed!==username){note("用户名不匹配，已取消");return}if(!confirm("最后确认：删除账号但保留文件？"))return;const r=await call(`/users/${id}`,{method:"DELETE",json:{username:typed,acknowledge:"我确认保留文件并删除账号"}});note(r.ok?"账号已删除，文件仍保留":(await r.json()).detail);loadOverview()}
async function review(id,approve){if(!confirm(approve?"通过该注册申请？":"拒绝该注册申请？"))return;const r=await call(`/requests/${id}/review`,{method:"POST",json:{approve}});note(r.ok?"申请已处理":(await r.json()).detail);loadOverview()}
$("addGroup").onclick=addGroup;$("addUser").onclick=addUser;$("refreshAdmin").onclick=loadOverview;$("fileUserSelect").onchange=()=>loadFiles("");
async function loadFiles(path){const id=$("fileUserSelect").value;if(!id){$("adminFilesBody").innerHTML="";return}const r=await call(`/users/${id}/files?path=${encodeURIComponent(path)}`);if(!r.ok){note((await r.json()).detail);return}const d=await r.json();filePath=d.path;renderBreadcrumb();$("adminFilesBody").innerHTML=d.entries.map(x=>`<tr><td>${x.type==="folder"?`<button class="folder-link" data-path="${esc(x.path)}">📁 ${esc(x.name)}</button>`:esc(x.name)}</td><td>${x.type==="folder"?"文件夹":"文件"}</td><td>${esc(x.content_display)}</td><td>${esc(x.size_display)}</td><td>${new Date(x.modified_at).toLocaleString("zh-CN")}</td></tr>`).join("")}
function renderBreadcrumb(){const parts=filePath?filePath.split("/"):[];let path="";$("adminBreadcrumb").innerHTML=`<button data-path="">全部文件</button>`+parts.map(p=>{path=path?`${path}/${p}`:p;return ` / <button data-path="${esc(path)}">${esc(p)}</button>`}).join("")}
$("adminFilesBody").onclick=e=>{const b=e.target.closest("[data-path]");if(b)loadFiles(b.dataset.path)};$("adminBreadcrumb").onclick=e=>{const b=e.target.closest("[data-path]");if(b)loadFiles(b.dataset.path)};
if(adminToken)showApp();else showLogin();
