const { createApp } = Vue;
const app=createApp({
  components:{
    UserTable:{props:["rows"],emits:["edit","toggle","delete"],template:`<el-table :data="rows"><el-table-column prop="username" label="用户名"/><el-table-column prop="class_name" label="用户组"/><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.status==='active'?'success':'info'">{{s.row.status==='active'?'正常':'已禁用'}}</el-tag></template></el-table-column><el-table-column prop="used_display" label="已用空间"/><el-table-column label="操作" width="250"><template #default="s"><el-button size="small" @click="$emit('edit',s.row)">修改</el-button><el-button size="small" @click="$emit('toggle',s.row)">{{s.row.status==='disabled'?'启用':'禁用'}}</el-button><el-button size="small" type="danger" plain @click="$emit('delete',s.row)">删除</el-button></template></el-table-column></el-table>`},
    FilterBar:{props:["groups","filter","total"],emits:["change","clear"],template:`<el-card class="filter-card"><el-form inline><el-form-item label="用户组"><el-select v-model="filter.class_id" clearable placeholder="全部用户组" @change="$emit('change')"><el-option v-for="g in groups" :key="g.id" :value="g.id" :label="g.name"/></el-select></el-form-item><el-form-item label="日期"><el-date-picker v-model="filter.date" type="date" value-format="YYYY-MM-DD" clearable @change="$emit('change')"/></el-form-item><el-form-item><el-button @click="$emit('clear')">清除筛选</el-button></el-form-item><b>筛选结果 {{total}} 条</b></el-form></el-card>`}
  },
  data:()=>({token:sessionStorage.getItem("school_admin")||"",loginName:"",loginPassword:"",loginError:"",notice:"",view:"dashboard",admins:[],classes:[],users:[],requests:[],reports:[],announcements:[],selectedGroup:"",userSearch:"",messageFilter:{class_id:"",date:""},fileGroup:"",path:"",entries:[],selected:[],recycle:[],logs:[],log:{class_id:"",user_id:"",action:"all",date:"",total:0},announcement:{class_ids:[],title:"",content:""},actions:[{id:"upload",label:"上传"},{id:"create",label:"新建"},{id:"download",label:"下载"},{id:"move",label:"移动"},{id:"rename",label:"重命名"},{id:"delete",label:"删除"},{id:"restore",label:"恢复"}]}),
  computed:{pathParts(){return this.path?this.path.split("/"):[]},currentGroup(){return this.classes.find(x=>String(x.id)===String(this.selectedGroup))},searchedUsers(){const q=this.userSearch.trim().toLowerCase();return q?this.users.filter(x=>x.username.toLowerCase().includes(q)):[]},filteredUsers(){return this.users.filter(x=>!this.log.class_id||x.class_id==this.log.class_id)},activeUsers(){return this.users.filter(x=>x.status==="active").length},pageTitle(){return ({dashboard:"概览",people:"用户组与用户",review:"注册审核",admins:"管理员",files:"用户组文件",recycle:"统一回收站",announcements:"公告管理",reports:"用户报告",logs:"操作日志"})[this.view]||"管理控制台"},allSelected(){return this.entries.length&&this.entries.every(x=>this.selected.includes(x.path))},hasUserRoot(){return this.selected.some(x=>!x.includes("/"))}},
  methods:{
    async api(url,opt={}){const headers=new Headers(opt.headers||{});if(this.token)headers.set("Authorization",`Bearer ${this.token}`);if(opt.json!==undefined){headers.set("Content-Type","application/json");opt.body=JSON.stringify(opt.json)}const r=await fetch(`/api/admin${url}`,{...opt,headers});if(r.status===401)this.logout();return r},
    async error(r){try{return (await r.json()).detail||"操作失败"}catch{return"操作失败"}}, note(t){this.notice=t;setTimeout(()=>{if(this.notice===t)this.notice=""},3000)}, date(v){return v?new Date(v).toLocaleString():"--"},statusLabel(s){return s==="active"?"正常":s==="disabled"?"已禁用":"待设置密码"},groupUsers(id){return this.users.filter(x=>x.class_id===id)},
    async login(){const r=await this.api("/login",{method:"POST",json:{username:this.loginName,password:this.loginPassword}});if(!r.ok){this.loginError=await this.error(r);return}this.token=(await r.json()).token;sessionStorage.setItem("school_admin",this.token);await this.load()},logout(){this.token="";sessionStorage.removeItem("school_admin")},
    async load(){const r=await this.api("/overview");if(!r.ok)return;const d=await r.json();this.admins=d.admins||[];this.classes=d.classes;this.users=d.students;this.requests=d.requests;this.reports=d.reports;this.announcements=d.announcements;if(!this.announcement.class_ids.length&&this.classes[0])this.announcement.class_ids=[this.classes[0].id];if(this.selectedGroup&&!this.currentGroup)this.selectedGroup=""},
    async open(v){this.view=v;if(v==="files")await this.loadFiles("");if(["review","reports","announcements"].includes(v))await this.loadMessages();if(v==="logs")await this.loadLogs();if(v==="recycle")await this.loadRecycle()},
    async addGroup(){const name=prompt("新用户组名称");if(!name)return;const r=await this.api("/classes",{method:"POST",json:{name}});this.note(r.ok?"用户组已创建":await this.error(r));await this.load()},async renameGroup(g){const name=prompt("新用户组名称",g.name);if(!name)return;const r=await this.api(`/classes/${g.id}`,{method:"PATCH",json:{name}});this.note(r.ok?"用户组及目录已改名":await this.error(r));await this.load()},async deleteGroup(g){if(!confirm("只能删除没有用户且目录为空的用户组，确认？"))return;const r=await this.api(`/classes/${g.id}`,{method:"DELETE"});this.note(r.ok?"用户组已删除":await this.error(r));await this.load()},async addUser(){if(!this.currentGroup)return this.note("请先选择用户组");const username=prompt("用户名");if(!username)return;const password=prompt("初始密码（至少6位）");if(password===null)return;const r=await this.api("/students",{method:"POST",json:{class_id:this.currentGroup.id,username,password}});this.note(r.ok?"用户已添加":await this.error(r));if(r.ok)await this.load()},async clearLoginAttempts(){const r=await this.api("/login-attempts/clear",{method:"POST"});if(!r.ok)return this.note(await this.error(r));this.note(`已清除全部 ${((await r.json()).cleared||0)} 条登录锁定记录`)},async addAdmin(){const username=prompt("管理员用户名（2至64位字母、数字、下划线或短横线）");if(!username)return;const password=prompt("管理员初始密码（至少6位）");if(password===null)return;const r=await this.api("/admins",{method:"POST",json:{username,password}});this.note(r.ok?"管理员已添加":await this.error(r));if(r.ok)await this.load()},async editAdmin(a){const username=prompt("管理员用户名",a.username);if(username===null)return;const password=prompt("新密码（留空不修改）","");if(password===null)return;const r=await this.api(`/admins/${a.id}`,{method:"PATCH",json:{username,password}});this.note(r.ok?"管理员已更新":await this.error(r));if(r.ok)await this.load()},async toggleAdmin(a){const status=a.status==="disabled"?"active":"disabled";if(status==="disabled"&&!confirm(`确认禁用管理员“${a.username}”吗？`))return;const r=await this.api(`/admins/${a.id}`,{method:"PATCH",json:{status}});this.note(r.ok?`管理员已${status==="active"?"启用":"禁用"}`:await this.error(r));if(r.ok)await this.load()},
    async editUser(u){const username=prompt("用户名",u.username);if(username===null)return;const class_id=Number(prompt("用户组ID\n"+this.classes.map(x=>`${x.id}: ${x.name}`).join("\n"),u.class_id));const password=prompt("新密码（不修改请留空）","");if(password===null)return;const r=await this.api(`/students/${u.id}`,{method:"PATCH",json:{username,class_id,password}});this.note(r.ok?"用户已更新":await this.error(r));await this.load()},async toggleUser(u){const r=await this.api(`/students/${u.id}`,{method:"PATCH",json:{status:u.status==="disabled"?"active":"disabled"}});this.note(r.ok?"用户状态已更新":await this.error(r));await this.load()},async deleteUser(u){if(!confirm(`确认删除用户“${u.username}”吗？其文件将移入回收站。`))return;const r=await this.api(`/students/${u.id}`,{method:"DELETE",json:{username:u.username,acknowledge:"我确认删除用户并将文件移入回收站"}});this.note(r.ok?"用户已删除":await this.error(r));await this.load()},
    async review(i,approve){const r=await this.api(`/requests/${i.id}/review`,{method:"POST",json:{approve}});this.note(r.ok?"申请已处理":await this.error(r));await this.load();await this.loadMessages()},async loadMessages(){const q=new URLSearchParams();if(this.messageFilter.class_id)q.set("class_id",this.messageFilter.class_id);if(this.messageFilter.date)q.set("date",this.messageFilter.date);const r=await this.api(`/messages?${q}`);if(!r.ok)return this.note(await this.error(r));const d=await r.json();this.requests=d.requests;this.reports=d.reports},clearMessageFilters(){this.messageFilter={class_id:"",date:""};this.loadMessages()},syncAnnouncement(){const first=this.announcements.find(x=>String(x.class_id)===String(this.announcement.class_ids[0]));this.announcement.title=first?.title||"";this.announcement.content=first?.content||""},async announce(){const r=await this.api("/announcements",{method:"POST",json:this.announcement});this.note(r.ok?"公告已更新":await this.error(r));if(r.ok)await this.load()},
    icon(i){if(i.type==="folder")return"📁";const e=i.name.split(".").pop().toLowerCase();return ["png","jpg","jpeg","gif","webp"].includes(e)?"🖼️":["doc","docx"].includes(e)?"📘":["xls","xlsx","csv"].includes(e)?"📗":e==="pdf"?"📕":"📄"},previewable(n){return/\.(png|jpe?g|gif|webp|svg|bmp|pdf|txt|md|csv|json|html?|mp3|wav|ogg|mp4|webm)$/i.test(n)},
    async loadFiles(p){if(!this.fileGroup){this.entries=[];return}const r=await this.api(`/classes/${this.fileGroup}/files?path=${encodeURIComponent(p)}`);if(!r.ok){this.note(await this.error(r));return}const d=await r.json();this.path=d.path;this.entries=d.entries;this.selected=[]},selectAll(e){this.selected=e.target.checked?this.entries.map(x=>x.path):[]},async openEntry(i){if(i.type==="folder")return this.loadFiles(i.path);if(this.previewable(i.name))return this.preview(i.path);this.download([i.path])},
    async upload(e){const f=new FormData();f.append("path",this.path);[...e.target.files].forEach(x=>{f.append("files",x);f.append("relative_paths",x.name)});const r=await this.api(`/classes/${this.fileGroup}/upload`,{method:"POST",body:f});this.note(r.ok?"上传完成":await this.error(r));e.target.value="";this.loadFiles(this.path)},async mkdir(){const name=prompt("文件夹名称");if(!name)return;const r=await this.api(`/classes/${this.fileGroup}/mkdir`,{method:"POST",json:{path:this.path,name}});this.note(r.ok?"文件夹已创建":await this.error(r));this.loadFiles(this.path)},async preview(p){const w=window.open("","_blank"),r=await this.api(`/classes/${this.fileGroup}/preview/start?path=${encodeURIComponent(p)}`,{method:"POST"});if(!r.ok){w?.close();this.note(await this.error(r));return}if(w)w.location.href=(await r.json()).url},async download(paths){const r=paths.length===1?await this.api(`/classes/${this.fileGroup}/download?path=${encodeURIComponent(paths[0])}`):await this.api(`/classes/${this.fileGroup}/batch-download`,{method:"POST",json:{paths}});if(!r.ok){this.note(await this.error(r));return}const a=document.createElement("a");a.href=URL.createObjectURL(await r.blob());a.download=paths.length===1?paths[0].split("/").pop():"用户组文件.zip";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},downloadSelected(){this.download(this.selected)},async renameSelected(){const p=this.selected[0],name=prompt("新名称",p.split("/").pop());if(!name)return;const r=await this.api(`/classes/${this.fileGroup}/rename`,{method:"POST",json:{path:p,name}});this.note(r.ok?"重命名完成":await this.error(r));this.loadFiles(this.path)},async moveSelected(){const user=this.selected[0].split("/")[0],destination=prompt("目标路径",user);if(destination===null)return;const r=await this.api(`/classes/${this.fileGroup}/move`,{method:"POST",json:{paths:this.selected,destination}});this.note(r.ok?"移动完成":await this.error(r));this.loadFiles(this.path)},async deleteSelected(){if(!confirm("确认移入回收站？"))return;const r=await this.api(`/classes/${this.fileGroup}/batch-delete`,{method:"POST",json:{paths:this.selected}});this.note(r.ok?"已移入回收站":await this.error(r));this.loadFiles(this.path)},
    logType(c){const a=String(c).split("：",1)[0];return this.actions.find(x=>a.startsWith(x.label))?.label||"其他"},async loadLogs(){const q=new URLSearchParams({action:this.log.action});if(this.log.class_id)q.set("class_id",this.log.class_id);if(this.log.user_id)q.set("user_id",this.log.user_id);if(this.log.date)q.set("date",this.log.date);const r=await this.api(`/logs?${q}`);if(!r.ok)return;const d=await r.json();this.logs=d.items;this.log.total=d.total},async loadRecycle(){const r=await this.api("/recycle");if(r.ok)this.recycle=(await r.json()).items},async restore(i){const r=await this.api(`/recycle/${i.id}/restore`,{method:"POST",json:{user_id:i.user_id}});this.note(r.ok?"已恢复":await this.error(r));this.loadRecycle()}
  },mounted(){if(this.token)this.load()}
});
app.use(ElementPlus).mount("#adminApp");
